# action.yml
name: "AI Code Reviewer"
description: "Use ChatGPT(O1) to review Pull Requests automatically."
author: "ChangHwan Lee"
runs:
  using: "docker"
  image: "Dockerfile"
  
inputs:
  GITHUB_TOKEN:
    description: "GitHub token for API calls."
    required: true
  OPENAI_API_KEY:
    description: "OpenAI API key for ChatGPT(O1)."
    required: true
  PR_NUMBER:
    description: "Pull Request number."
    required: true
  SYSTEM_PROMPT:
    description: "System prompt for ChatGPT(O1)."
    required: false
